name: my_bridge
from_domain: 5
to_domain: 0
topics:
  camera_pkg/left/compressed_image:
    type: sensor_msgs/msg/CompressedImage

  camera_pkg/right/compressed_image:
    type: sensor_msgs/msg/CompressedImage

  odom:
    type: nav_msgs/msg/Odometry
  
  scan:
    type: sensor_msgs/msg/LaserScan
  
  tf:
    type: tf2_msgs/msg/TFMessage

  tf_static:
    type: tf2_msgs/msg/TFMessage

  imu/data_raw:
    type: sensor_msgs/msg/Imu